### ISSUE TITLE
Dynamic Array Implementation

### ISSUE THREAD

**Issue by benjamincommeau2** [mpaland/avl_array#2]
Hello Marco Paland

I think your code is great. For my specific use case I need a dynamic array implementation of your code. Do you know if anyone else has an implementation of your code using dynamic arrays such as vectors, lists, or deques? I tried naively modifying your code to allow dynamic arrays and it proved to be more challenging than I thought. Thank you for time and consideration.

Sincerely,

Benjamin Commeau

**Comment by mpaland** [comment]
Hello Benjamin,

no, I don't know any dynamic implementation of my code. The standard implementation would be std::map, of course.

Anyway, modifying the code to be dynamic is not so complicated. I would suggest to use std::vector as dynamic storage container:
```c++
std::vector<Key> key_;               // node key
std::vector<T> val_;                 // node value
std::vector<std::int8_t> balance_;   // subtree balance
std::vector<child_type> child_;      // node childs
size_type   size_;                   // actual size
size_type   root_;                   // root node
std::vector<size_type> parent_;      // node parent, use one element if not needed (zero sized array is not allowed)
```
In the insert() routine you can use push_back and you have to resize all vectors above to store the according size.
As you can access a vector via the [ ] operator, you shouldn't have to modify much more code, IMHO.

Edit:
And of course you need to use and set the template `Size` parameter as variable, which contains the actual vector size.
